### ISSUE TITLE
pytessearct is not properly detecting words that surrounded by highlight 

### ISSUE THREAD

**Issue by bee-mcc** [CIS3296SoftwareDesignF21/prj-01-openhighlightcopypaste#30]
pytessearct does not draw boundary boxes around/detect some words in images which contain highlight. 

Cecily please check above description for accuracy and write steps to reproduce a version of the bug.

**Comment by bee-mcc** [comment]
https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html

**Comment by cecilydev** [comment]
Looking at opencv gaussian algorithm to clean up image (after removing highlight), per suggestion in article.

**Comment by bee-mcc** [comment]
Cecily worked to fix this - image preprocessing before OCR implemented in PR #42 fixed
